name: Python CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Получение кода
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Запуск unit-тестов
        run: python test_calculator.py